config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:index,:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  attr_reader :remember_token, :activation_token, :reset_token

  validates :email, presence: true,
    length: {maximum: Settings.user_valid.max_email_length},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :name, length: {maximum: Settings.user_valid.max_name_length},
    presence: true
  validates :password, presence: true,
    length: {minimum: Settings.user_valid.min_pass_length}, allow_nil: true

  before_create :create_activation_digest
  before_save :email_downcase
  has_secure_password

  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id",
    dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id",
    dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  scope :activated, ->{where activated: true}

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    @remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update remember_digest: nil
  end

  def activate
    update activated: true, activated_at: Time.zone.now
  end

  def current_user? user
    self == user
  end

  def create_reset_digest
    @reset_token = User.new_token
    update reset_digest: User.digest(reset_token), reset_send_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_send_at < Settings.password_reset_expire.hours.ago
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  private

  def email_downcase
    self.email = email.downcase
  end

  def create_activation_digest
    @activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :find_user, only: %i(show edit update destroy)
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def index
    @users = User.activated.paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      @user.send_activation_email
      flash[:info] = t "account_activate.check_email_for_active"
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @follow = current_user.active_relationships.build
    @unfollow = current_user.active_relationships.find_by followed_id: @user.id
    @microposts = Micropost.feed_for(@user).paginate page: params[:page]
  rescue ActiveRecord::RecordNotFound
    render "errors/error_404"
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t "flash.profile_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "delete.success"
    else
      flash[:error] = t "delete.fail"
    end
    redirect_to users_url
  end

  private

  def find_user
    @user = User.find_by id: params[:id]
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def correct_user
    find_user
    redirect_to(root_url) unless @user.current_user? current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: 50
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_with model: @follow, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t("following.submit"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @user.current_user? current_user %>
  <div id="follow_form">
    <% if current_user.following? @user %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, url: yield(:form_path), local: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, t("update.name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t("update.email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t("update.password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t("update.password_confirm") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: @unfollow, html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit t("following.unfollow"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.gravatar_imagine_size %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !user.current_user?(current_user) && !user.admin? %>
    | <%= link_to t("all_user.delete"), user, method: :delete,
      data: { confirm: I18n.t("all_user.you_sure") } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("update.edit_user") %>
<h1><%= t "update.update_profile" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% provide :button_text, t("update.save_change") %>
    <% provide :form_path, user_path(@user) %>
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, t("all_user.all_user")) %>
<h1><%= t "all_user.all_user" %></h1>

<%= will_paginate @collection, previous_label: t("paginate.previous"),
  next_label: t("paginate.next") %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @collection, previous_label: t("paginate.previous"),
  next_label: t("paginate.next") %>

app/views/users/new.html.erb
<% provide :title, t(:sign_up) %>
<h1><%= t :sign_up %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% provide :button_text, t("sign_up_form.create_account") %>
    <% provide :form_path, signup_path %>
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render "follow_form" if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= t("micropost.microposts") %> (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t(:view_my_profile), @user %></span>
      <span>
        <b><%= t "micropost.microposts" %>:</b> <%= @user.microposts.count %>
      </span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: Settings.follow_gravatar_size),
              user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate @users%>
    <% end %>
  </div>
</div>